Add files via upload
dig-eg-gaz/content pull request #962
Opened 2022-09-02 17:42 UTC by alexmgrove

2022-09-16 16:47 UTC, whanley reviewed
This is good, but can you add `status="verified"` tags to the divs you corrected? Aim for about 25.

2022-10-12 02:23 UTC, whanley requested changes
Good start on the deliverable, Alex. Read over page 3 carefully and make sure it's divided into the appropriate items and they come in the proper sequence. To do this, you need to have your page image and your xml text and make sure they correspond to each other.
As far as verification, there are also some details to be cleared up. If you've dealt with a comment, remove it. Don't change the status of every item in a section like Local and General. Verify the whole section once it's correct.

2022-10-12 02:23 UTC, whanley commented on 1906-12-01.xml
> +                        <!-- The header was misspelled -->
if this problem has been solved, you can delete the comment

2022-10-12 02:23 UTC, whanley commented on 1906-12-01.xml
> +                        <!-- Missing on this page before 3.1.6 A nile Wreck>   -->
has this been solved?

2022-10-12 02:23 UTC, whanley commented on 1906-12-01.xml
> +                        <p>The census of the Bedonins is the first to be taken in the case of the
Bedouins

2022-10-12 02:23 UTC, whanley commented on 1906-12-01.xml
> +                        <head>Honeaty Rowarded</head>
there are misspellings in the headline. Don't say it's verified if it isn't!

2022-10-12 02:23 UTC, whanley commented on 1906-12-01.xml
>                      <p>Gazotto's Special Sorvloe.)</p>
spelling mistakes--don't say it's verified if it isn't.

2022-10-12 02:23 UTC, whanley commented on 1906-12-01.xml
> +                    <!-- mispelled words -->
has this been solved?

2022-10-12 02:23 UTC, whanley commented on 1904-12-22.xml
> +                    <date when="2022-09-09">September 9, 2019</date>
also change the date in black

2022-10-12 02:23 UTC, whanley commented on 1904-12-22.xml
> +                    <date when="1904-12-22">Thursday, July 13, 1905</date>
also change the date in black

2022-10-12 02:23 UTC, whanley commented on 1904-12-22.xml
> +                        <hi rend="bold">The interesting article on the port of Alex andria from the
remove the bold highlight

2022-10-12 02:23 UTC, whanley commented on 1904-12-22.xml
> +                            the quays would be far too</hi>
surely the page doesn't end like this?

2022-10-26 01:45 UTC, whanley commented
Okay, this is fine. Now how about the deliverables?

2022-10-26 01:46 UTC, alexmgrove commented
I'm on it, will be done with a few by the end of the week.
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Will Hanley ***@***.***>
Sent: Tuesday, October 25, 2022 9:45:30 PM
To: dig-eg-gaz/content ***@***.***>
Cc: Alexander Grove ***@***.***>; Author ***@***.***>
Subject: Re: [dig-eg-gaz/content] Add files via upload (PR #962)


Okay, this is fine. Now how about the deliverables?

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/dig-eg-gaz/content/pull/962*issuecomment-1291372229__;Iw!!PhOWcWs!0m8Ysdkxv-M9zlggb3eeIK81pg-jXq2lpesKFOxkBwwHw8dgHp4q4JcqVZ4YLOajH3XJqqjqUe5_NfrjkT9cKcay$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/A2X74KUTTEEXED2534TCEQDWFCELVANCNFSM6AAAAAAQDO4CCI__;!!PhOWcWs!0m8Ysdkxv-M9zlggb3eeIK81pg-jXq2lpesKFOxkBwwHw8dgHp4q4JcqVZ4YLOajH3XJqqjqUe5_NfrjkYcag_wW$>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-12-04 03:18 UTC, merged

2022-12-04 03:19 UTC, alexmgrove commented
What does this mean?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Will Hanley ***@***.***>
Sent: Saturday, December 3, 2022 10:18:45 PM
To: dig-eg-gaz/content ***@***.***>
Cc: Alexander Grove ***@***.***>; Author ***@***.***>
Subject: Re: [dig-eg-gaz/content] Add files via upload (PR #962)


Merged #962<https://urldefense.com/v3/__https://github.com/dig-eg-gaz/content/pull/962__;!!PhOWcWs!0mirHRvBghfbmKkQ4OwTALyFBaUPsmD3f69TKAtif_XYz3umnkeLZ20nPK2spZ-2eD-AuYYaoo5dAo9fRoTr7SMj$> into master.

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/dig-eg-gaz/content/pull/962*event-7947464831__;Iw!!PhOWcWs!0mirHRvBghfbmKkQ4OwTALyFBaUPsmD3f69TKAtif_XYz3umnkeLZ20nPK2spZ-2eD-AuYYaoo5dAo9fRvANUuL2$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/A2X74KSWXWAXYGL7TWUNLT3WLQERLANCNFSM6AAAAAAQDO4CCI__;!!PhOWcWs!0mirHRvBghfbmKkQ4OwTALyFBaUPsmD3f69TKAtif_XYz3umnkeLZ20nPK2spZ-2eD-AuYYaoo5dAo9fRrXccrf1$>.
You are receiving this because you authored the thread.Message ID: ***@***.***>